### PR TITLE
Fix deleting of AMIs, fixes #311

### LINKED ISSUE #311: machine_image recreation fails randomly
Simple code:

```ruby
machine_image "my-ami" do
  recipe "my-recipe"
  action [:destroy, :create]
end
```

Works in 50% of cases. In other 50 returns:

```
[2015-09-04T14:18:18+00:00] ERROR: machine_image[my-ami] (fyber-environments::_rebuild_base_images line 3) had an error: AWS::Core::Resource::NotFound: aws_image[base-ami] (ami-15745262) (basic_chef_client::block line 451) had an error: AWS::Core::Resource::NotFound: unable to find the instance
```

Is it related to the fact that AMIs always have `From-instance` tag that is never flushed and thus chef-provisioning-aws tries to destroy image from this tag even though it doesn't exist already?

### PR DESCRIPTION
**Pull request by Fodoj**
Previous implementation was checking against `AWS::EC2::Errors::InvalidInstanceID::NotFound` exception, which is listed as a valid exception in AWS docs. In reality, though, actual exception AWS returns is `AWS::Core::Resource::NotFound`. 

Previous implementation worked by accident, because if you create and then instantly delete an image, then instance is still around with terminated state, but if you try to create now and then delete in few hours, then  `AWS::Core::Resource::NotFound` will be returned and recipe will fail.

That the exact reason of this issue: https://github.com/chef/chef-provisioning-aws/issues/311 appearing. Now it's fixed.

### CODE REVIEW

**Comment by tyler-ball** [comment]
Great catch @Fodoj !

File: spec/integration/machine_image_spec.rb [hunk 1]
```diff
@@ -25,6 +25,42 @@
           name: 'test_machine_image'
         ).and be_idempotent
       end
+
+      describe 'action :destroy' do
```
Comment (tyler-ball) [inline spec/integration/machine_image_spec.rb]: This should be `describe 'action :destroy', :super_slow do` to mark this test as super slow

File: spec/integration/machine_image_spec.rb [hunk 2]
```diff
@@ -25,6 +25,42 @@
...
+              action :destroy
+            end
+          }
+          expect(r).to destroy_an_aws_image('test_machine_image'
+          ).and be_idempotent
+        end
+
+        it "deletes the image if instance is gone long time ago" do
+          image = driver.ec2_resource.images({filters: [ { name: "name", values: ["test_machine_image"] }]}).first
+          image.create_tags(tags: [{key: "from-instance", value: "i-4e5b71e8"}])
```
Comment (tyler-ball) [inline spec/integration/machine_image_spec.rb]: Will you make this `i-12345678` so it is more obvious that this should be a bogus id?

**Comment by tyler-ball** [comment]
A few minor comments and one more request:  please add `machine_image_spec.rb` to the [Rakefile](https://github.com/chef/chef-provisioning-aws/blob/master/Rakefile#L42) so we start running this integration test through CI.

Don't worry about the Travis failures - its because Travis does not load secure environment variables for forks.  I'll run the CI when merging to master.

**Comment by Fodoj** [comment]
@tyler-ball thanks for the review, changes are pushed
