### PR TITLE
Fix handling of lb server certificates, fixes #258

### LINKED ISSUE #258: Elastic Load Balancers: SSL works on create, but not update
```
    load_balancer "#{env_name}" do
      machines web_machines
      load_balancer_options subnets: subnets,
                            security_groups: [load_balancer_sg],
                            listeners: [{
                                            instance_port: 8080,
                                            protocol: 'HTTP',
                                            instance_protocol: 'HTTP',
                                            port: 80
                                        },
                            {
                                instance_port: 8080,
                                protocol: 'HTTPS',
                                instance_protocol: 'HTTP',
                                port: 443,
                                ssl_certificate_id: "arn:aws:iam::360965486607:server-certificate/cloudfront/foreflight-2015-07-09"
                            }
                            ]
    end
```

This will work the first time, but fail every time after with the error

```
    AWS::Core::OptionGrammar::FormatError
    -------------------------------------
    expected string value for option ssl_certificate_id
```

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, if a user specified an ARN for the `server_certificate` key
in a listener spec, the LB creation would succeed, but future updates
would always update the server_certificate.  If the user specified an
ARN for the `ssl_certificate_id`, the creation would succeed, but future
updates would fail.  Here we support both.

### CODE REVIEW

**Comment by stevendanna** [comment]
Likely also fixes #258 for most people.

File: lib/chef/provisioning/aws_driver/driver.rb [hunk 1]
```diff
@@ -360,6 +361,31 @@ def allocate_load_balancer(action_handler, lb_spec, lb_options, machine_specs)
       end
     end
 
+    # Compare two server certificates by casting them both to strings.
```
Comment (tyler-ball) [inline lib/chef/provisioning/aws_driver/driver.rb]: Can you update this comment with `The parameters should either be a String containing the certificate ARN, or a IAM::ServerCertificate object.`

Comment (stevendanna) [inline lib/chef/provisioning/aws_driver/driver.rb]: That's not strictly true, but sure ;)

**Comment by tyler-ball** [comment]
One comment comment, and we should update the README to contain the following below [Machine Options](https://github.com/chef/chef-provisioning-aws#machine-options)

```markdown
# Load Balancer Options

You can configure the ELB options by setting `with_load_balancer_options` or specifying them on each `load_balancer` resource.

```ruby
machine 'test1'
m2 = machine 'test2'
load_balancer "my_elb" do
  machines ['test1', m2]
  load_balancer_options({
    subnets: subnets,
    security_groups: [load_balancer_sg],
    listeners: [
      {
          instance_port: 8080,
          protocol: 'HTTP',
          instance_protocol: 'HTTP',
          port: 80
      },
      {
          instance_port: 8080,
          protocol: 'HTTPS',
          instance_protocol: 'HTTP',
          port: 443,
          ssl_certificate_id: "arn:aws:iam::360965486607:server-certificate/cloudfront/foreflight-2015-07-09"
      }
    ]
  })
```

The available parameters for `load_balancer_options` can be viewed at http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client.html#create_load_balancer-instance_method .  

NOTES:
1.  You can specify either `ssl_certificate_id` or `server_certificate` in a listener but the value to both parameters should be the ARN of an existing IAM::ServerCertificate object.
1.  Instead of specifying `tags` in the `load_balancer_options`, you should specify `aws_tags`.  See the note on [tagging base resources](https://github.com/chef/chef-provisioning-aws#base-resources).
```

After that I'm :+1: on this PR and we can close #258!

File: README.md [hunk 2]
```diff
@@ -139,6 +139,42 @@ with_machine_options({
...
+      }
+    ]
+  })
+\```
+
+The available parameters for `load_balancer_options` can be viewed at http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client.html#create_load_balancer-instance_method .
+
+NOTES:
+1.  You can specify either `ssl_certificate_id` or `server_certificate` in a listener but the value to both parameters should be the ARN of an existing IAM::ServerCertificate object.
+1.  Instead of specifying `tags` in the `load_balancer_options`, you should specify `aws_tags`.  See the note on [tagging base resources](https://github.com/chef/chef-provisioning-aws#base-resources).
```
Comment (tylercloke) [inline README.md]: This should probably be a 2? :P

Comment (stevendanna) [inline README.md]: The markdown renderer will turn it into a 2.  Saves you from having to update the list evertime you want to change the order of the notes.
