### PR TITLE
use wait_for_state before tagging VPC's, fixes #218

### LINKED ISSUE #218: Failure when attempting to tag an aws_vpc
There appears to be a similar issue experienced with instances in #158 when attempting to tag the vpc.

```

[2015-05-29T11:15:11-04:00] INFO: [AWS EC2 400 0.037725 0 retries] create_tags(:resources=>["vpc-e1cef184"],:tags=>[{:key=>"Name",:value=>"testchef-vpc"}]) AWS::EC2::Errors::InvalidVpcID::NotFound The vpc ID 'vpc-e1cef184' does not exist

[2015-05-29T11:15:11-04:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/aws_vpc/testchef-vpc

    
    ================================================================================
    Error executing action `create` on resource 'aws_vpc[testchef-vpc] (no AWS object id)'
    ================================================================================
    
    AWS::EC2::Errors::InvalidVpcID::NotFound
    ----------------------------------------
    The vpc ID 'vpc-e1cef184' does not exist
    
    Resource Declaration:
    ---------------------
    # In /root/chef-repo/.chef/local-mode-cache/cache/cookbooks/chef-provisioning-aws/recipes/default.rb
    
     14:   aws_vpc "testchef-vpc" do
     15:     cidr_block "10.40.20.0/22"
     16:     internet_gateway true
     17:   end
     18: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-repo/.chef/local-mode-cache/cache/cookbooks/chef-provisioning-aws/recipes/default.rb:14:in `from_file'
    
    aws_vpc("testchef-vpc") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      driver #<Chef::Provisioning::AWSDriver::Driver:0x0000000d8e9358 @driver_url="aws::us-east-1", @config={:log_level=>:info, :log_location=>#<IO:<STDOUT>>, :node_name=>"administrator", :client_key=>"/root/chef-repo/.chef/administrator.pem", :validation_client_name=>"chef-validator", :validation_key=>"/root/chef-repo/.chef/chef-validator.pem", :chef_server_url=>"chefzero://localhost:8889", :syntax_check_cache_path=>"/root/.chef/syntaxcache", :cookbook_path=>"/root/chef-repo/.chef/local-mode-cache/cache/cookbooks", :encrypted_data_bag_secret=>"/root/chef-repo/.chef/encrypted_data_bag_secret", :force_logger=>false, :force_formatter=>false, :color=>true, :local_mode=>true, :override_runlist=>[#<Chef::RunList::RunListItem:0x00000004f0bed8 @version=nil, @type=:recipe, @name="chef-provisioning-aws::default">], :config_file=>"/root/chef-repo/.chef/knife.rb", :specific_recipes=>[], :repo_mode=>"hosted_everything", :formatters=>[], :event_handlers=>[], :start_handlers=>[], :authentication_protocol_version=>"1.0"}, @aws_credentials=#<Chef::Provisioning::AWSDriver::Credentials:0x0000000d8e9240 @credentials={"default"=>{:aws_access_key_id=>"xxxx", :aws_secret_access_key=>"xxxx", :name=>"default"}}>, @aws_config=<AWS::Core::Configuration>, @ec2=<AWS::EC2>>
      chef_server {:chef_server_url=>"chefzero://localhost:8889", :options=>{:client_name=>"administrator", :signing_key_filename=>"/root/chef-repo/.chef/administrator.pem"}}
      declared_type :aws_vpc
      cookbook_name "chef-provisioning-aws"
      recipe_name "default"
      cidr_block "10.40.20.0/22"
      internet_gateway true
    end
    
[2015-05-29T11:15:11-04:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/aws_vpc/testchef-vpc
[2015-05-29T11:15:11-04:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/aws_vpc/testchef-vpc
[2015-05-29T11:15:11-04:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-05-29T11:15:11-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-29T11:15:11-04:00] ERROR: Exception handlers complete
[2015-05-29T11:15:11-04:00] FATAL: Stacktrace dumped to /root/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 5.712035763 seconds
[2015-05-29T11:15:11-04:00] ERROR: aws_vpc[testchef-vpc] (no AWS object id) (chef-provisioning-aws::default line 14) had an error: AWS::EC2::Errors::InvalidVpcID::NotFound: The vpc ID 'vpc-e1cef184' does not exist
[2015-05-29T11:15:12-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Attempting to rerun this will create a duplicate VPC and will occasionally run successfully, it looks like the time in between requesting the resource and it being available is causing the failure.

### PR DESCRIPTION
**Pull request by metadave**
Some AWS objects don't have a "status" value, but a "state" (such as an AWS VPC). This PR adds a `wait_for_state` method in `AwsProvider`. This method is called before trying to tag a VPC to prevent a race when the VPC may be in `pending` state.

fixes https://github.com/chef/chef-provisioning-aws/issues/218

### CODE REVIEW

File: lib/chef/provisioning/aws_driver/aws_provider.rb [hunk 1]
```diff
@@ -288,5 +288,30 @@ def wait_for_status(aws_object, expected_status, acceptable_errors = [], tries=6
...
+    current_state = aws_object.state
+
+    Retryable.retryable(:tries => tries, :sleep => sleep, :on => StatusTimeoutError) do |retries, exception|
+      action_handler.report_progress "waited #{retries*sleep}/#{tries*sleep}s for #{aws_object.id} state to change to #{expected_states.inspect}..."
+      begin
+        current_state = aws_object.state
+        unless expected_states.include?(current_state)
+          raise StatusTimeoutError.new(aws_object, current_state, expected_states)
+        end
+      rescue *acceptable_errors
```
Comment (randomcamel) [inline lib/chef/provisioning/aws_driver/aws_provider.rb]: Kinda cool that this is happy even when `acceptable_errors` is empty.

**Comment by Jimflip** [comment]
We are getting a lot of InvalidVpcID etc, which makes the whole system unreliable.
This fix is critical.

**Comment by andrewelizondo** [comment]
:+1:

**Comment by Jimflip** [comment]
The internet gateway for VPC vpc-0fb93a6a never obtained existence seem to be increasing, perhaps due to the load at AWS (does seem to fluctuate with time of day). But effectively this is making the entire use of chef-provisioning in our CI system unusable.

An ETA on merge would be good so I can judge if moving to the branch is best option.

**Comment by Jimflip** [comment]
Using the branch I still seem to have the same issues:

AWS::EC2::Errors::InvalidVpcID::NotFound
09-Jul-2015 14:32:53	----------------------------------------
09-Jul-2015 14:32:53	The vpc ID 'vpc-56ed6f33' does not exist
09-Jul-2015 14:32:53	
09-Jul-2015 14:32:53	Resource Declaration:
09-Jul-2015 14:32:53	---------------------
09-Jul-2015 14:32:53	# In /home/bamboo/bamboo-agent-home/xml-data/build-dir/CHCL-PTRD-JOB1/aws/vpc.rb
09-Jul-2015 14:32:53	
09-Jul-2015 14:32:53	  9: aws_vpc VPC do
09-Jul-2015 14:32:53	 10:   cidr_block '10.0.0.0/24'
09-Jul-2015 14:32:53	 11:   internet_gateway true
09-Jul-2015 14:32:53	 12:   main_routes '0.0.0.0/0' => :internet_gateway
09-Jul-2015 14:32:53	 13:   enable_dns_hostnames true
09-Jul-2015 14:32:53	 14:   enable_dns_support true
09-Jul-2015 14:32:53	 15: end

**Comment by metadave** [comment]
@Jimflip I'm going to merge this fix, but I'll submit a Github issue to track further VPC issues (and CC you)
